### ISSUE TITLE
Report Demo Outpatient Thermal Receipt improvements

### ISSUE THREAD

**Issue by jarbaugh** [OpenHMIS/reports#1]
The demo Outpatient Thermal Receipt includes specifications for Windows fonts.  This causes the report to not be able to render when running on a Linux server.  Manually editing the XML and removing the font specifications (just the font name) corrects the problem.

Also, you should probably not show voided names.
for example try...
    LEFT OUTER JOIN person_name patient_person_name ON
        patient_person.person_id = patient_person_name.person_id AND
        patient_person_name.preferred = 1 AND
        patient_person_name.voided = 0

**Comment by dubdabasoduba** [comment]
@akmad for the Fonts issue I ran into it once but if the the restricted-extras in linux are installed the the issue is corrected.

**Comment by akmad** [comment]
Yeah, but maybe we shouldn't require those fonts? Also, what about the voided names?

**Comment by dubdabasoduba** [comment]
I am looking into the voided names. I just created an issue on our issue tracker for it. As for the fonts we can agree on one universal font thats available in the three platforms  i.e. windows, linux & mac

**Comment by akmad** [comment]
Regarding a universal font... that is a good idea. I'd suggest creating a issue to find one and update our reports.

Please post links to the issues you create here so that I can look it up in the future.

**Comment by dubdabasoduba** [comment]
http://issues.openhmisafrica.org/issue/jas-16 The link to the Voided name Issue

**Comment by dubdabasoduba** [comment]
http://issues.openhmisafrica.org/issue/jas-17 The link to the universal Fonts Issue

**Comment by akmad** [comment]
Great, thanks!
